name: compile abcm2ps

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build abcm2ps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Prepare compilation prerequisites
        run: sudo apt-get install build-essential

      - name: configure
        run: cd abcm2ps && ./configure

      - name: make
        run: make -C abcm2ps CFLAGS=-DA4_FORMAT=1
        
      - name: move abcm2ps out of submodule directory
        run: mkdir -p converter && mv abcm2ps/abcm2ps converter/

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit compiled abcm2ps (A4 output)
          file_pattern: converter/abcm2ps
